[tool.poetry]
name = "betterproto"
version = "1.2.5"
description = "A better Protobuf / gRPC generator & library"
authors = ["Daniel G. Taylor <danielgtaylor@gmail.com>"]
readme = "README.md"
repository = "https://github.com/danielgtaylor/python-betterproto"
keywords = ["protobuf", "gRPC"]
license = "MIT"

exclude = ["betterproto/tests"]

[tool.poetry.dependencies]
python = "^3.6"
backports-datetime-fromisoformat = { version = "^1.0.0", python = "<3.7" }
black = { version = "^19.10b0", optional = true }
dataclasses = { version = "^0.7", python = ">=3.6, <3.7" }
grpclib = "^0.3.1"
jinja2 = { version = "^2.11.2", optional = true }
protobuf = { version = "^3.12.2", optional = true }
stringcase = "^1.2.0"

[tool.poetry.dev-dependencies]
mypy = "^0.770"
pytest = "^5.4.2"
pytest-asyncio = "^0.12.0"
pytest-cov = "^2.9.0"
tox = "^3.15.1"

[tool.poetry.scripts]
protoc-gen-python_betterproto = "betterproto.plugin:main"

[tool.poetry.extras]
compiler = ["black", "jinja2", "protobuf"]

[tool.black]
target-version = ['py36']

[tool.coverage.run]
omit = ["betterproto/tests/*"]

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = true
envlist = py36, py37

[testenv]
whitelist_externals = poetry
commands =
    poetry install -v --extras compiler
    poetry run pytest --cov betterproto
"""

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

